import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "relative bg-[#1b1b1b] h-full font-sans antialiased",
          fontSans.variable
        )}
      >
        <main className="relative flex flex-col min-h-screen">
          <div className="flex-grow flex-1">
            {children}
            <Toaster />
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
